//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BessoneResultados.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIPTA
    {
        public string PTA { get; set; }
        public string ORI { get; set; }
        public string SER { get; set; }
        public string STA_PRT { get; set; }
        public string MED { get; set; }
        public string MAT { get; set; }
        public string PRF { get; set; }
        public string EST_PAC { get; set; }
        public string EST_TEC { get; set; }
        public Nullable<short> REC_PAC { get; set; }
        public Nullable<short> REC_TEC { get; set; }
        public Nullable<short> REC_INS { get; set; }
        public Nullable<short> REC_RBO { get; set; }
        public Nullable<short> REC_FAC { get; set; }
        public Nullable<short> REC_GRD { get; set; }
        public string TXT_1 { get; set; }
        public string TXT_2 { get; set; }
        public string MMB_LET { get; set; }
        public string ENC_LET { get; set; }
        public string EST_LET { get; set; }
        public string MET_LET { get; set; }
        public string PIE_LET { get; set; }
        public Nullable<short> MMB_LIN { get; set; }
        public Nullable<short> ENC_LIN { get; set; }
        public string MMB_POS { get; set; }
        public Nullable<short> ENC_ANC { get; set; }
        public Nullable<short> ENC_MIZ { get; set; }
        public Nullable<short> EST_MIZ { get; set; }
        public string PIE_TXT_1 { get; set; }
        public string PIE_TXT_2 { get; set; }
        public string IPR { get; set; }
        public string GUA { get; set; }
        public string TXT_I { get; set; }
        public string TXT_F { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public Nullable<System.DateTime> FEG { get; set; }
        public string CNF_ORD { get; set; }
        public string TIP_PRE { get; set; }
        public string DES { get; set; }
        public string CMP_PRE { get; set; }
        public Nullable<short> DEP { get; set; }
        public string FME { get; set; }
        public Nullable<short> MGN_LFT { get; set; }
        public Nullable<short> MGN_RGT { get; set; }
        public string SOM { get; set; }
        public string MEQ_RIS { get; set; }
        public string MOD_RIS { get; set; }
        public Nullable<short> PRT { get; set; }
        public string ACT { get; set; }
        public string REC_ETQ { get; set; }
        public string PRC { get; set; }
        public Nullable<int> UNE { get; set; }
        public string FIR { get; set; }
        public string VRF_AUT { get; set; }
        public string FEN { get; set; }
        public string STA { get; set; }
        public string ANA { get; set; }
        public Nullable<short> REC_CPR { get; set; }
        public string PRT_ETQ { get; set; }
        public string TXT_3 { get; set; }
        public string TXT_4 { get; set; }
        public string EST { get; set; }
        public string CHK_DOC { get; set; }
    }
}
