//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BessoneResultados.Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATATECHEntities : DbContext
    {
        public DATATECHEntities()
            : base("name=DATATECHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIPTA> CLIPTA { get; set; }
        public virtual DbSet<ESTUDIOS_ENVIADOS> ESTUDIOS_ENVIADOS { get; set; }
        public virtual DbSet<vw_Estudios> vw_Estudios { get; set; }
        public virtual DbSet<vw_Estudios_Enviados> vw_Estudios_Enviados { get; set; }
    }
}
