//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BessoneResultados.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIOS_ENVIADOS
    {
        public long ID { get; set; }
        public string PTA { get; set; }
        public int ORD { get; set; }
        public string PAC { get; set; }
        public string MAI { get; set; }
        public System.DateTime ENV { get; set; }
    }
}
