//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BessoneResultados.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Estudios
    {
        public string PTA { get; set; }
        public int NRO { get; set; }
        public string TIT { get; set; }
        public string COD { get; set; }
        public string TXT { get; set; }
        public System.DateTime FEC { get; set; }
        public Nullable<int> NDO { get; set; }
        public string NOM { get; set; }
        public string MAI { get; set; }
        public string DES { get; set; }
        public string PRF { get; set; }
        public string ARC_FIR { get; set; }
    }
}
